### ISSUE TITLE
补全函数后，函数括号内输入变量时无法自动补全

### ISSUE THREAD

**Issue by zhanghan12345** [jokervTv/ncl-vscode-support#3]
补全函数后，函数括号内输入变量时无法自动补全，删掉自动补全的括号后手动打上括号，变量的自动补全才可用

**Comment by yongpz** [comment]
函数补全时，默认会有一次全部变量的选定，可以使用 tab 在变量间切换，此时变量的自动补全默认是无法使用的，按一次 esc 就可以启用了（如图），不知道您说的是不是这个问题，如果不是的话，可否麻烦你上传 gif 便于我重现问题
![tempVar](https://user-images.githubusercontent.com/29646575/119266464-89fc0300-bc1d-11eb-9e26-cd2af851b81c.gif)

**Comment by zhanghan12345** [comment]
已经解决，非常感谢您的回复🤙，这个问题解决以后可以从sublime 转vscode了-------- 原始邮件 --------发件人： Yongpeng Zhang ***@***.***>日期： 2021年5月23日周日 半夜11:22收件人： jokervTv/ncl-vscode-support ***@***.***>抄送： zhanghan12345 ***@***.***>, Author ***@***.***>主    题： Re: [jokervTv/ncl-vscode-support] 补全函数后，函数括号内输入变量时无法自动补全 (#3)
函数补全时，默认会有一次全部变量的选定，可以使用 tab 在变量间切换，此时变量的自动补全默认是无法使用的，按一次 esc 就可以启用了（如图），不知道您说的是不是这个问题，如果不是的话，可否麻烦你上传 gif 便于我重现问题
